pacvim: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    src/helperFns.cpp:103:17:
      error: format not a string literal and no format arguments [-Werror=format-security]
      103 |         mvprintw(TOP+5, 0, (x).c_str());
          |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

Let's wrap all the missing places with "%s" format.